export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST'
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL'

export const GET_SINGLE_POST_REQUEST = 'GET_SINGLE_POST_REQUEST'
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS'
export const GET_SINGLE_POST_FAIL = 'GET_SINGLE_POST_FAIL'

export const GET_ALL_REVIEWS_REQUEST = 'GET_ALL_REVIEWS_REQUEST'
export const GET_ALL_REVIEWS_SUCCESS = 'GET_ALL_REVIEWS_SUCCESS'
export const GET_ALL_REVIEWS_FAIL = 'GET_ALL_REVIEWS_FAIL'

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEWS_REQUEST'
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEWS_SUCCESS'
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEWS_FAIL'


export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'